version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          spec: cypress/integration/login.feature
          filters:
            branches:
              only:
                - master
          post-steps:
            - store_artifacts:
                path: cypress/report
            - store_test_results:
                path: cypress/results
    
    nightly:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
